// https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags
// !!! Needs to be completed
export const opentypeLanguageTagsToISO639 = {
  "ABA ": "aba", // Abé
  "ABK ": "abk", // Abkhazian
  "ACH ": "ach", // Acoli
  "ACR ": "acr", // Achi
  "AFK ": "afr", // Afrikaans
  "AKA ": "aka", // Akan
  "ALS ": "gsw", // Alsatian (Swiss German)
  "ALT ": "alt", // Southern Altai
  "AMH ": "amh", // Amharic
  "ARG ": "arg", // Aragonese
  "ASM ": "asm", // Assamese
  "AST ": "ast", // Asturian
  "ATH ": "apk", // Athapascan
  "AZB ": "azb", // South Azerbaijani
  "AZE ": "aze", // Azerbaijani
  "BEL ": "bel", // Belarusian
  "BEM ": "bem", // Bemba
  "BEN ": "ben", // Bengali
  "BOS ": "bos", // Bosnian
  "BRE ": "bre", // Breton
  "BUL ": "bul", // Bulgarian
  "CAT ": "cat", // Catalan
  "CEB ": "ceb", // Cebuano
  "CHE ": "che", // Chechen
  "CHG ": "chg", // Chagatai
  "CHP ": "chp", // Chipewyan
  "CHU ": "chu", // Church Slavic
  "CHV ": "chv", // Chuvash
  "CNI ": "cni", // Asháninka
  "COP ": "cop", // Coptic
  "CRE ": "cre", // Cree
  "CZE ": "ces", // Czech
  "DAN ": "dan", // Danish
  "DAR ": "dar", // Dargwa
  "DEU ": "deu", // German
  "DGR ": "dgr", // Dogrib
  "DJE ": "dje", // Zarma
  "DSB ": "dsb", // Lower Sorbian
  "DUT ": "nld", // Dutch
  "DZN ": "dzo", // Dzongkha
  "ENG ": "eng", // English
  "EST ": "est", // Estonian
  "EWE ": "ewe", // Ewe
  "FAR ": "fas", // Persian
  "FJI ": "fij", // Fijian
  "FIN ": "fin", // Finnish
  "FRA ": "fra", // French
  "FRI ": "fry", // Frisian
  "FUL ": "ful", // Fulah
  "GEO ": "kat", // Georgian
  "GLG ": "glg", // Galician
  "GRE ": "ell", // Modern Greek
  "GUJ ": "guj", // Gujarati
  "HAI ": "hai", // Haida
  "HAU ": "hau", // Hausa
  "HAW ": "haw", // Hawaiian
  "HEB ": "heb", // Hebrew
  "HIN ": "hin", // Hindi
  "HRV ": "hrv", // Croatian
  "HUN ": "hun", // Hungarian
  "HYE ": "hye", // Armenian
  "IBO ": "ibo", // Igbo
  "ICE ": "isl", // Icelandic
  "IND ": "ind", // Indonesian
  "IRI ": "gle", // Irish
  "ITA ": "ita", // Italian
  "JPN ": "jpn", // Japanese
  "KAN ": "kan", // Kannada
  "KAT ": "kat", // Georgian
  "KAZ ": "kaz", // Kazakh
  "KHM ": "khm", // Khmer
  "KIK ": "kik", // Kikuyu
  "KIN ": "kin", // Kinyarwanda
  "KIR ": "kir", // Kirghiz
  "KOR ": "kor", // Korean
  "LAO ": "lao", // Lao
  "LAT ": "lat", // Latin
  "LIT ": "lit", // Lithuanian
  "LTZ ": "ltz", // Luxembourgish
  "LUB ": "lub", // Luba-Katanga
  "LUG ": "lug", // Ganda
  "LVI ": "lav", // Latvian
  "MAD ": "mad", // Madura
  "MAG ": "mag", // Magahi
  "MAH ": "mah", // Marshallese
  "MKD ": "mkd", // Macedonian
  "MAI ": "mai", // Maithili
  "MAL ": "mal", // Malayalam
  "MLG ": "mlg", // Malagasy
  "MLT ": "mlt", // Maltese
  "MOL ": "ron", // Moldavian
  "MON ": "mon", // Mongolian
  "MRI ": "mri", // Maori
  "NEP ": "nep", // Nepali
  "NOR ": "nor", // Norwegian
  "ORI ": "ori", // Odia
  "ORM ": "orm", // Oromo
  "PAN ": "pan", // Punjabi
  "PER ": "fas", // Persian
  "POL ": "pol", // Polish
  "POR ": "por", // Portuguese
  "RUM ": "ron", // Romanian
  "RUS ": "rus", // Russian
  "SWE ": "swe", // Swedish
  "TAM ": "tam", // Tamil
  "TEL ": "tel", // Telugu
  "THA ": "tha", // Thai
  "TUR ": "tur", // Turkish
  "UKR ": "ukr", // Ukrainian
  "URD ": "urd", // Urdu
  "VIE ": "vie", // Vietnamese
  "YOR ": "yor", // Yoruba
  "ZHO ": "zho", // Chinese
  "ZUL ": "zul", // Zulu
} as const;
